{{- range $configMapName, $configMap := .Values.configMaps }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $configMapName }}
  labels:
    {{- include "deployment-tools.labels" $ | nindent 4 }}
  {{- with $configMap.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  {{- toYaml $configMap.data | nindent 2 }}
---
{{- end }}