apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
  name: git-credentials
  namespace: jenkins
  annotations:
    jenkins.io/credentials-description: Git credentials from Kubernetes secret
  labels:
    type: git
    jenkins.io/credentials-type: usernamePassword
data:
  username: <base64 encoded username>
  password: <base64 encoded token>
