master:
  installPlugins:
    - kubernetes:latest
    - kubernetes-credentials-provider:latest
    - workflow-job:latest
    - workflow-aggregator:latest
    - credentials-binding:latest
    - git:latest
  resources:
    requests:
      cpu: "50m"
      memory: "256Mi"
    limits:
      cpu: "1"
      memory: "512Mi"
  slaveKubernetesNamespace: jenkins
persistence:
  enabled: false
namespaceOverride: jenkins