master:
  installPlugins:
    - kubernetes:latest
    - kubernetes-credentials-provider:latest
    - workflow-job:latest
    - workflow-aggregator:latest
    - credentials-binding:latest
    - git:latest
#agent:
# envVars:
#   resources:
#     requests:
#       cpu: "50m"
#       memory: "1024Mi"
#     limits:
#       cpu: "1"
#       memory: "3500Mi"
#   javaOpts: "-Xms3500m -Xmx3500m"
#   serviceType: ClusterIP
# agent:
#   resources:
#     requests:
#       cpu: "500m"
#       memory: "256Mi"
#     limits:
#       cpu: "1"
#       memory: "512Mi"
# serviceAccount:
#   name: cd-jenkins
# persistence:
#   storageClass: jenkins-pv
#   size: 5Gi
persistence:
  existingClaim: jenkins-pv-claim