apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: deploy-tools
  name: deploy-permissions
rules:
- apiGroups: ["", "batch", "extensions", "apps", "networking.k8s.io"] # "" indicates the core API group
  resources: ["*"]
  verbs: ["*"]