apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins
  namespace: deploy-tools
subjects:
- kind: ServiceAccount
  name: jenkins # "name" is case sensitive
  namespace: deploy-tools
roleRef:
  kind: Role #this must be Role or ClusterRole
  name: deploy-permissions # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io