master:
  ingress:
    annotations:
      ingress.bluemix.net/redirect-to-https: "True"  
    tls:
    - hosts:
      - jenkins.<hostname>
      secretName: <ingress_secret>
    enabled: false
    hostName: jenkins.<hostname>
  installPlugins:
    - kubernetes:latest
    - kubernetes-credentials-provider:latest
    - workflow-job:latest
    - workflow-aggregator:latest
    - credentials-binding:latest
    - git:latest
    - artifactory:latest
  resources:
    requests:
      cpu: "50m"
      memory: "256Mi"
    limits:
      cpu: "1"
      memory: "512Mi"
  slaveKubernetesNamespace: jenkins
persistence:
  enabled: false
  # existingClaim: jenkins-pv-claim
namespaceOverride: jenkins