# Helm chart values for a springboot app
# Default values for deployment-tools.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

service:
  type: ClusterIP
  port: 80
  targetPort: 8080
containerPort: 8080

healthCheck: true
livenessProbe:
  path: /sample
  initialDelaySeconds: 0 
readinessProbe:
  path: /sample

# Specified by the command-line (--set image.tag=<version>)
#image:
#  tag: 2

image:
  # repository: us.icr.io/samskubetut/deployment-tools
  pullPolicy: Always

imagePullSecrets:
  - name: container-registry
nameOverride: ""
fullnameOverride: ""

# volumeMounts for the deployment
volumeMounts:
  - name: config
    mountPath: /config

# volumes for the deployment
volumes:
  - name: config
    configMap:
      name: sample

# secrets to be injected into the environment
secrets:
  # - secretRef:
  #     name: springboot-secrets

configMaps: {}


        
nodeSelector: {}

tolerations: []

affinity: {}

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

ingress:
  enabled: false
  # annotations:
  #   ingress.bluemix.net/redirect-to-https: "True"
  # hosts:
  #   - host: <hostURL>
  #     paths:
  #       - /
  # tls:
  #  - secretName: <tlsSecret>
  #    hosts:
  #      - <hostURL>

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi